### PR TITLE
Add Chinese translate

### PR DESCRIPTION
**Pull request by ItsDApples**
Hey, i notice this amazing mod. i love this feature really well. can i add a translate for it?
btw i cant understand the Config X and the Config Y mean , so i havent change it, can you tell me whats it means?
another question, can I transfer it to MCMOD (The largest Minecraft mod website)? This can help more people learn about this practical mod.
Thanks for this nice mod

### CODE REVIEW

**Comment by LordEnder-Kitty** [comment]
I'm glad to hear that people like my mod. I sort of made this because there are mods that add similar and smaller features but there was nothing that added everything and made it all compatible.
I'd be glad to add some translations. Also, as for the settings you couldn't understand, Config Button X and Config Button Y change the position values of the config button in the vanilla settings screen. It's basically just XYZ coordinates, but XY because it's 2d. Hope that made sense. 
As for reuploading, I have never heard of the site you speak of. I looked it up and, I mean, I can't read anything, cause it's Chinese. I don't know how the site works, but I'd rather not have people uploading my stuff.

Anyway. Feel free to figure out the remaining translations, and whenever I get around to updating this, I'll try and see if I can add the translation.

**Comment by ItsDApples** [comment]
I will edit the language file and update it accordingly. 
For the website, it is similar to Modrinth or CurseForge in China, but it is designed for obtaining mod information(That because we often cant visit Modrinth and CurseForge for the network problem). It simply adds mod information to the platform, with Chinese language support, and the mod's author will be prominently featured
Thank you for your reply.

**Comment by LordEnder-Kitty** [comment]
Would that mean that the actual files are being uploaded elsewhere though? You said it's just information. If all it is is a description of what the mod does, I suppose that would be fine but not if the files are being uploaded and downloaded in a place I'm not associated with.

**Comment by ItsDApples** [comment]
This is optional, I won't upload anything other than module information. and provide all links(Github , Curseforge , Modrinth)

**Comment by LordEnder-Kitty** [comment]
Just finished the update to 1.21.5. Added a new feature with some new stuff to translate if you wanna do that.

(Also sorry it took so long to update. I was procrastinating and learning the bass guitar. lol)

**Pull request merged**
